### ISSUE TITLE
Documentation links not working

### ISSUE THREAD

**Issue by packet-rat** [SmartDataAnalytics/DL-Learner#46]
# Links to documentation on dl-learner.org and here do not work:

http://dl-learner.org/files/dl-learner-manual.pdf
http://jens-lehmann.org/files/2009_dllearner_sparql.pdf

**Comment by SimonBin** [comment]
thanks for your report, can you help me there for a second where is the broken 2nd link?

**Comment by JensLehmann** [comment]
Should be http://jens-lehmann.org/files/2009/dllearner_sparql.pdf and http://dl-learner.org/Resources/Documents/manual.pdf .
