### ISSUE TITLE
Bug in heuristic computation of CELOE

### ISSUE THREAD

**Issue by aris-github** [SmartDataAnalytics/DL-Learner#62]
https://github.com/SmartDataAnalytics/DL-Learner/blob/7f3af9181b8c69cca5e19f32e25ea341b8f4c8f9/components-core/src/main/java/org/dllearner/algorithms/celoe/OEHeuristicRuntime.java#L66

Hi @JensLehmann @LorenzBuehmann @SimonBin , I am using DL-Learner for my research. I found a bug in the heuristic computation in the above line: the accuracy gain is wrong, it shall be conversely computed as: 

```
 score += (score - parentAccuracy) * gainBonusFactor; 
```

**Comment by LorenzBuehmann** [comment]
Hi Yingbing Hua,

seems like you're right. The formula for the *accuracy gain* is
```
acc_gain(C) = acc_c(C, t) − acc_c(C′, t)
```
with `C` being the current concept and `C´ it's parent in the refinement tree.

**Comment by LorenzBuehmann** [comment]
@kit-hua Has been fixed in `develop` branch. thank you very much for the bug report.
